import { prepareLeaveRequest } from '../helpers/prep.ts';

const tests = [
  {
    name: 'Leaves list field validation',
    user: 'admin',
    method: 'GET',
    url: '/api/leaves',
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'data', type: 'exists', message: 'data array must exist' },
      { path: 'data.0.id', type: 'uuid', message: 'data[0].id must be a valid UUID' },
      { path: 'data.0.staff.id', type: 'notNull', message: 'staff.id must not be null' },
      { path: 'data.0.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
      { path: 'count', type: 'notNull', message: 'count must be present' },
    ],
  },
  {
    name: 'Create department response validation',
    user: 'admin',
    method: 'POST',
    url: '/api/departments',
    data: {
      name: 'Frontend Test Auto',
      description: 'string',
      parentID: '37dffcf3-8ef9-4c6a-a4b7-930b9aaadbc0',
      locationID: 'eb7634e7-74e0-451a-8dd0-037d70d10821',
      work_schedule: {
        work_start_time: '09:00',
        work_end_time: '18:00',
        lunch_start_time: '12:00',
        lunch_end_time: '13:00',
      },
      status: 1,
      leave_day: 0,
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 201, message: 'status must be 201' },
      { path: 'data.id', type: 'uuid', message: 'id must be a valid UUID' },
      { path: 'data.name', type: 'equals', expected: 'Frontend Test Auto', message: 'name must match input' },
      { path: 'data.parent.id', type: 'uuid', message: 'parent.id must be a valid UUID' },
      { path: 'data.location.id', type: 'uuid', message: 'location.id must be a valid UUID' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
      { path: 'data.leave_day', type: 'equals', expected: 14, message: 'leave_day must be 14' },
      { path: 'data.work_schedule.work_start_time', type: 'equals', expected: '09:00', message: 'work_start_time must be 09:00' },
      { path: 'data.work_schedule.work_end_time', type: 'equals', expected: '18:00', message: 'work_end_time must be 18:00' },
    ],
  },
  {
    name: 'Departments list validation',
    user: 'admin',
    method: 'GET',
    url: '/api/departments',
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data', type: 'exists', message: 'data array must exist' },
      { path: 'data.0.id', type: 'uuid', message: 'first department id must be valid UUID' },
      { path: 'data.0.name', type: 'notNull', message: 'first department name must not be null' },
      { path: 'data.0.parent.id', type: 'uuid', message: 'parent.id must be valid UUID' },
      { path: 'data.0.location.id', type: 'uuid', message: 'location.id must be valid UUID' },
      { path: 'data.0.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
      { path: 'count', type: 'equals', expected: 41, message: 'count must be 41' },
    ],
  },
  {
    name: 'Departments tree validation',
    user: 'admin',
    method: 'GET',
    url: '/api/departments/tree',
    assertions: [
      { path: '0.id', type: 'uuid', message: 'root department id must be valid UUID' },
      { path: '0.name', type: 'notNull', message: 'root name must not be null' },
      { path: '0.work_schedule.work_start_time', type: 'equals', expected: '09:00', message: 'work_start_time must be 09:00' },
      { path: '0.children', type: 'exists', message: 'children must exist' },
      { path: '0.staff.0.email', type: 'notNull', message: 'first staff email must not be null' },
      { path: '0.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
    ],
  },
  {
    name: 'Department detail validation',
    user: 'admin',
    method: 'GET',
    url: '/api/departments/932eea8a-af1f-4ae9-8507-31fbd99d819a?withChildren=true&withStaff=true&withPermission=true&permissionFormat=FULL',
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'department id must be valid UUID' },
      { path: 'data.name', type: 'notNull', message: 'department name must not be null' },
      { path: 'data.location.id', type: 'uuid', message: 'location.id must be valid UUID' },
      { path: 'data.children.0.id', type: 'uuid', message: 'first child id must be valid UUID' },
      { path: 'data.staff.0.email', type: 'notNull', message: 'first staff email must not be null' },
      { path: 'data.leave_day', type: 'equals', expected: 14, message: 'leave_day must be 14' },
    ],
  },
  {
    name: 'Update department validation',
    user: 'admin',
    method: 'PATCH',
    url: '/api/departments/932eea8a-af1f-4ae9-8507-31fbd99d819a',
    data: {
      name: 'İnsan Kaynakları',
      description: 'string',
      locationID: '1272c1a3-bbba-4515-be9c-6a6c69aa35ee',
      work_schedule: {
        work_start_time: '09:00',
        work_end_time: '18:00',
        lunch_start_time: '12:00',
        lunch_end_time: '13:00',
      },
      status: 1,
      leave_day: 0,
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'department id must be valid UUID' },
      { path: 'data.name', type: 'equals', expected: 'İnsan Kaynakları', message: 'name must match' },
      { path: 'data.location.id', type: 'uuid', message: 'location.id must be valid UUID' },
      { path: 'data.leave_day', type: 'equals', expected: 0, message: 'leave_day must be 0 after update' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
    ],
  },
  {
    name: 'Delete department validation',
    user: 'admin',
    method: 'DELETE',
    url: '/api/departments/264c657e-ed07-4022-ae92-eb3f64c5b541',
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.message', type: 'equals', expected: 'operation.success', message: 'message must be operation.success' },
    ],
  },
  {
    name: 'Update department supervisor validation',
    user: 'admin',
    method: 'PUT',
    url: '/api/departments/932eea8a-af1f-4ae9-8507-31fbd99d819a/supervisor',
    data: {
      userID: 'd81d76b2-2341-4e28-901f-443866f59e98',
      status: 1,
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'department id must be valid UUID' },
      { path: 'data.supervisor.user.id', type: 'uuid', message: 'supervisor user id must be valid UUID' },
      { path: 'data.supervisor.status', type: 'in', expected: [0, 1, 2], message: 'supervisor status must be in [0,1,2]' },
      { path: 'data.leave_day', type: 'equals', expected: 0, message: 'leave_day must stay 0' },
    ],
  },
  {
    name: 'Staff portal departments list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/departments',
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data', type: 'exists', message: 'data array must exist' },
      { path: 'data.0.id', type: 'uuid', message: 'first department id must be valid UUID' },
      { path: 'data.0.name', type: 'notNull', message: 'first department name must not be null' },
      { path: 'data.0.parent.id', type: 'uuid', message: 'parent.id must be valid UUID' },
      { path: 'data.0.location.id', type: 'uuid', message: 'location.id must be valid UUID' },
      { path: 'data.0.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
      { path: 'count', type: 'equals', expected: 40, message: 'count must be 40' },
    ],
  },
  {
    name: 'Staff portal departments tree validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/departments/tree',
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'root department id must be valid UUID' },
      { path: 'data.0.name', type: 'notNull', message: 'root name must not be null' },
      { path: 'data.0.work_schedule.work_start_time', type: 'equals', expected: '09:00', message: 'work_start_time must be 09:00' },
      { path: 'data.0.children', type: 'exists', message: 'children must exist' },
      { path: 'data.0.staff.0.email', type: 'notNull', message: 'first staff email must not be null' },
      { path: 'data.0.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
      { path: 'count', type: 'equals', expected: 100, message: 'count must be 100' },
    ],
  },
  {
    name: 'Staff portal profile validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/profile',
    assertions: [
      { path: 'data.id', type: 'uuid', message: 'profile id must be valid UUID' },
      { path: 'data.email', type: 'equals', expected: 'john.doe@company.com', message: 'email must match' },
      { path: 'data.employment.position', type: 'equals', expected: 'Senior Software Developer', message: 'position must match' },
      { path: 'data.employment.is_fulltime', type: 'equals', expected: true, message: 'is_fulltime must be true' },
      { path: 'data.education.schools.0.name', type: 'notNull', message: 'first school name must not be null' },
      { path: 'data.domain.id', type: 'uuid', message: 'domain id must be valid UUID' },
    ],
  },
  {
    name: 'Staff portal profile photo upload validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/profile-photo',
    headers: {
      accept: 'application/json',
      'Content-Type': 'multipart/form-data',
    },
    data: {
      file: '@dummy.png',
    },
    assertions: [
      { path: 'id', type: 'uuid', message: 'file id must be valid UUID' },
      { path: 'name', type: 'equals', expected: 'profile-photo.jpg', message: 'name must match' },
      { path: 'category', type: 'equals', expected: 'PROFILE_PHOTO', message: 'category must be PROFILE_PHOTO' },
    ],
  },
  {
    name: 'Staff portal profile photo fetch validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/profile-photo',
    headers: {
      accept: 'application/json',
    },
    assertions: [
      { path: 'id', type: 'uuid', message: 'file id must be valid UUID' },
      { path: 'name', type: 'equals', expected: 'profile-photo.jpg', message: 'name must match' },
      { path: 'category', type: 'equals', expected: 'PROFILE_PHOTO', message: 'category must be PROFILE_PHOTO' },
    ],
  },
  {
    name: 'Staff portal profile photo delete validation',
    user: 'staff',
    method: 'DELETE',
    url: '/api/staff-portal/profile-photo',
    headers: {
      accept: 'application/json',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'message', type: 'equals', expected: 'string', message: 'message must be string' },
    ],
  },
  {
    name: 'Staff portal find staff validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/find-staff',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data', type: 'exists', message: 'data array must exist' },
      { path: 'data.0.id', type: 'uuid', message: 'first staff id must be valid UUID' },
      { path: 'data.0.full_name', type: 'notNull', message: 'full_name must not be null' },
      { path: 'count', type: 'equals', expected: 10, message: 'count must be 10' },
    ],
  },
  {
    name: 'Staff portal staffs list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/staffs',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data', type: 'exists', message: 'data array must exist' },
      { path: 'data.0.id', type: 'uuid', message: 'first staff id must be valid UUID' },
      { path: 'data.0.email', type: 'equals', expected: 'adem.ertekin@demo.com', message: 'first staff email must match' },
      { path: 'count', type: 'equals', expected: 298, message: 'count must be 298' },
    ],
  },
  {
    name: 'Staff portal staff files validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/staff-files',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'file id must be valid UUID' },
      { path: 'data.0.staff_id', type: 'uuid', message: 'staff_id must be valid UUID' },
      { path: 'data.0.document_type', type: 'equals', expected: 'RESUME', message: 'document_type must be RESUME' },
      { path: 'count', type: 'equals', expected: 100, message: 'count must be 100' },
    ],
  },
  {
    name: 'Staff portal upload file validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/upload-file',
    headers: {
      accept: 'application/json',
      'Content-Type': 'multipart/form-data',
    },
    data: {
      file: '@dummy.png',
      name: 'Resume - John Doe',
      document_type: 'RESUME',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'file id must be valid UUID' },
      { path: 'data.document_type', type: 'equals', expected: 'RESUME', message: 'document_type must be RESUME' },
    ],
  },
  {
    name: 'Staff portal profile info update validation',
    user: 'staff',
    method: 'PATCH',
    url: '/api/staff-portal/profile/profile-info',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      gender: 'male',
      about: 'Experienced software developer with 5 years of experience',
      address: {
        country: 'Türkiye',
        city: 'İstanbul',
        district: 'Kadıköy',
        address: 'Barbaros Bulvarı No:145 D:5',
      },
      birth_date: '1990-01-15',
      marital_status: 'single',
      child_number: 2,
      emergency: {
        name: 'Jane Doe',
        phone_number: '5551234567',
      },
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.success', type: 'equals', expected: true, message: 'inner success must be true' },
      { path: 'data.message', type: 'equals', expected: 'Profile updated successfully', message: 'message must match' },
      { path: 'data.staff_id', type: 'uuid', message: 'staff_id must be valid UUID' },
    ],
  },
  {
    name: 'Staff portal request leave validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/request-leave',
    prepare: prepareLeaveRequest,
    headers: {
      accept: 'application/json',
      'Content-Type': 'multipart/form-data',
    },
    data: {
      // start/end dates + staffID will be injected by prepareLeaveRequest
      start_date: '{{start_date}}',
      end_date: '{{end_date}}',
      staffID: '{{staff_id}}',
      leaving_type: 'ANNUAL_LEAVE',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 201, message: 'status must be 201' },
      { path: 'data.id', type: 'uuid', message: 'leave id must be valid UUID' },
      { path: 'data.type', type: 'equals', expected: 'ANNUAL_LEAVE', message: 'type must be ANNUAL_LEAVE' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
      { path: 'data.number_of_days', type: 'equals', expected: 1.75, message: 'number_of_days must be 1.75' },
    ],
  },
  {
    name: 'Staff portal leave requests list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/leave-requests',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'leave id must be valid UUID' },
      { path: 'data.0.type', type: 'equals', expected: 'ANNUAL_LEAVE', message: 'type must be ANNUAL_LEAVE' },
      { path: 'summary.totalRemaining', type: 'equals', expected: 14, message: 'totalRemaining must be 14' },
      { path: 'count', type: 'equals', expected: 1, message: 'count must be 1' },
    ],
  },
  {
    name: 'Staff portal assignments list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/assignments',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'assignment id must be valid UUID' },
      { path: 'data.0.staff.id', type: 'uuid', message: 'staff.id must be valid UUID' },
      { path: 'data.0.project.id', type: 'uuid', message: 'project.id must be valid UUID' },
      { path: 'data.0.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
      { path: 'count', type: 'equals', expected: 1, message: 'count must be 1' },
    ],
  },
  {
    name: 'Staff portal assignment OTP send validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/assignments/{{assignment_id}}/approve/send-otp',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 201, message: 'status must be 201' },
      { path: 'data.message', type: 'equals', expected: 'OTP başarıyla gönderildi.', message: 'message must match' },
      { path: 'message', type: 'equals', expected: 'OTP başarıyla gönderildi.', message: 'outer message must match' },
    ],
  },
  {
    name: 'Staff portal assignment approve validation',
    user: 'staff',
    method: 'PATCH',
    url: '/api/staff-portal/assignments/{{assignment_id}}/approve',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      otpCode: '999999',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'assignment id must be valid UUID' },
      { path: 'data.project.id', type: 'uuid', message: 'project id must be valid UUID' },
      { path: 'data.type', type: 'in', expected: [0, 1, 2, 3], message: 'type must be within allowed values' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
    ],
  },
  {
    name: 'Staff portal assignment reject validation',
    user: 'staff',
    method: 'PATCH',
    url: '/api/staff-portal/assignments/{{assignment_id}}/reject',
    headers: {
      accept: 'application/json',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'assignment id must be valid UUID' },
      { path: 'data.project.id', type: 'uuid', message: 'project id must be valid UUID' },
      { path: 'data.status', type: 'equals', expected: 2, message: 'status must be 2 (rejected)' },
    ],
  },
  {
    name: 'Staff portal projects list validation',
    user: 'admin',
    method: 'GET',
    url: '/api/staff-portal/projects',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'project id must be valid UUID' },
      { path: 'data.0.name', type: 'notNull', message: 'project name must not be null' },
      { path: 'count', type: 'equals', expected: 2, message: 'count must be 2' },
    ],
  },
  {
    name: 'Staff portal project detail validation',
    user: 'admin',
    method: 'GET',
    url: '/api/staff-portal/projects/28ea03cb-19c0-46f2-9a13-44f21ab94ded',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'project id must be valid UUID' },
      { path: 'data.name', type: 'equals', expected: 'KAS', message: 'project name must match' },
      { path: 'data.domainID', type: 'uuid', message: 'domainID must be valid UUID' },
    ],
  },
  {
    name: 'Staff portal announcements list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/announcements',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'announcement id must be valid UUID' },
      { path: 'data.0.title', type: 'notNull', message: 'title must not be null' },
      { path: 'data.0.image_file.url', type: 'notNull', message: 'image_file.url must not be null' },
      { path: 'count', type: 'equals', expected: 100, message: 'count must be 100' },
    ],
  },
  {
    name: 'Staff portal entrust list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/entrust',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'entrust id must be valid UUID' },
      { path: 'data.0.asset.id', type: 'uuid', message: 'asset id must be valid UUID' },
      { path: 'data.0.status', type: 'in', expected: [0, 1, 2, 3, 4, 5, 6, 7, 8], message: 'status must be a known value' },
      { path: 'count', type: 'equals', expected: 100, message: 'count must be 100' },
    ],
  },
  {
    name: 'Staff portal entrust grouped validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/entrust/grouped',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.groupID', type: 'notNull', message: 'groupID must not be null' },
      { path: 'data.0.data.0.id', type: 'uuid', message: 'nested entrust id must be valid UUID' },
      { path: 'data.0.data.0.asset.id', type: 'uuid', message: 'nested asset id must be valid UUID' },
      { path: 'count', type: 'equals', expected: 25, message: 'count must be 25' },
    ],
  },
  {
    name: 'Staff portal entrust detail validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/entrust/{{entrust_id}}',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'entrust id must be valid UUID' },
      { path: 'data.groupID', type: 'uuid', message: 'groupID must be valid UUID' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2, 3, 4, 5, 6, 7, 8], message: 'status must be known' },
    ],
  },
  {
    name: 'Staff portal entrust send otp validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/entrust/send-otp',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      groupID: '5b129778-38aa-4847-96c6-c1f25c6e16b9',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.otpId', type: 'uuid', message: 'otpId must be valid UUID' },
      { path: 'data.expiryMinutes', type: 'equals', expected: 10, message: 'expiryMinutes must be 10' },
      { path: 'message', type: 'equals', expected: 'OTP kodu telefonunuza başarıyla gönderildi', message: 'message must match' },
    ],
  },
  {
    name: 'Staff portal entrust verify validation',
    user: 'staff',
    method: 'PATCH',
    url: '/api/staff-portal/entrust/verify',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      entrustID: 'string',
      groupID: 'string',
      entrustIDs: [null],
      otpCode: '123456',
      action: 'approve',
      response_note: 'string',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'entrust id must be valid UUID' },
      { path: 'data.groupID', type: 'uuid', message: 'groupID must be valid UUID' },
      { path: 'data.asset.id', type: 'uuid', message: 'asset id must be valid UUID' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2, 3, 4, 5, 6, 7, 8], message: 'status must be known' },
    ],
  },
  {
    name: 'Staff portal expenses list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/expenses',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'expense group id must be valid UUID' },
      { path: 'data.0.project.id', type: 'uuid', message: 'project id must be valid UUID' },
      { path: 'data.0.total_amount', type: 'equals', expected: 400, message: 'total_amount must be 400' },
      { path: 'data.0.expenses.0.id', type: 'uuid', message: 'expense item id must be valid UUID' },
      { path: 'count', type: 'equals', expected: 1, message: 'count must be 1' },
    ],
  },
  {
    name: 'Staff portal expense tags validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/expenses/tags',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'tag id must be valid UUID' },
      { path: 'data.0.name', type: 'notNull', message: 'tag name must not be null' },
      { path: 'count', type: 'equals', expected: 4, message: 'count must be 4' },
    ],
  },
  {
    name: 'Staff portal expense detail validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/expenses/{{expense_group_id}}',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'expense group id must be valid UUID' },
      { path: 'data.project.id', type: 'uuid', message: 'project id must be valid UUID' },
      { path: 'data.expenses.0.id', type: 'uuid', message: 'expense item id must be valid UUID' },
      { path: 'data.total_amount', type: 'equals', expected: 400, message: 'total_amount must be 400' },
    ],
  },
  {
    name: 'Staff portal expense group tag create validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/expense-group-tags',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      name: 'Test Automatcoin',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 201, message: 'status must be 201' },
      { path: 'data.id', type: 'uuid', message: 'tag id must be valid UUID' },
      { path: 'data.name', type: 'equals', expected: 'Test Automatcoin', message: 'name must match' },
    ],
  },
  {
    name: 'Staff portal expense group tags list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/expense-group-tags',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'tag id must be valid UUID' },
      { path: 'data.0.name', type: 'notNull', message: 'tag name must not be null' },
      { path: 'count', type: 'equals', expected: 5, message: 'count must be 5' },
    ],
  },
  {
    name: 'Staff portal overtime request creation validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/overtime-requests',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      extra_hours: 2,
      overtime_date: '2025-12-02',
      note: 'string',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 201, message: 'status must be 201' },
      { path: 'data.id', type: 'uuid', message: 'overtime id must be valid UUID' },
      { path: 'data.extra_hours', type: 'equals', expected: 2, message: 'extra_hours must be 2' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
    ],
  },
  {
    name: 'Staff portal overtime requests list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/overtime-requests',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'overtime request id must be valid UUID' },
      { path: 'data.0.extra_hours', type: 'equals', expected: 2, message: 'extra_hours must be 2' },
      { path: 'count', type: 'equals', expected: 1, message: 'count must be 1' },
    ],
  },
  {
    name: 'Staff portal advance request creation validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/advance-request',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      note: 'Araba Alcam',
      amount: 5000,
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 201, message: 'status must be 201' },
      { path: 'data.id', type: 'uuid', message: 'advance id must be valid UUID' },
      { path: 'data.amount', type: 'equals', expected: 5000, message: 'amount must be 5000' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
    ],
  },
  {
    name: 'Staff portal advance requests list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/advance-requests',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'advance id must be valid UUID' },
      { path: 'data.0.amount', type: 'equals', expected: 5000, message: 'amount must be 5000' },
      { path: 'count', type: 'equals', expected: 1, message: 'count must be 1' },
    ],
  },
  {
    name: 'Staff portal checkin status validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/checkin-status',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.is_logged', type: 'equals', expected: false, message: 'is_logged must be false' },
    ],
  },
  {
    name: 'Staff portal checkin validation',
    user: 'staff',
    method: 'POST',
    url: '/api/staff-portal/checkin',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      longitude: 36.81883,
      latitude: 39.9115,
      qr_code: 'ABC123XYZ',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.tracking_id', type: 'uuid', message: 'tracking_id must be valid UUID' },
      { path: 'data.operation_type', type: 'equals', expected: 'check-in', message: 'operation_type must be check-in' },
      { path: 'data.duration_minutes', type: 'equals', expected: 480, message: 'duration_minutes must be 480' },
    ],
  },
  {
    name: 'Staff portal attendance records validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/attendance-records',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'attendance id must be valid UUID' },
      { path: 'data.0.duration_minutes', type: 'equals', expected: 480, message: 'duration_minutes must be 480' },
      { path: 'count', type: 'equals', expected: 100, message: 'count must be 100' },
    ],
  },
  {
    name: 'Staff portal shifts list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/shifts?startDate=2025-09-01&endDate=2025-09-30',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.date', type: 'equals', expected: '2025-09-01', message: 'first date must be 2025-09-01' },
      { path: 'data.0.is_active', type: 'equals', expected: true, message: 'is_active must be true' },
    ],
  },
  {
    name: 'Staff portal payrolls list validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/payrolls',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'payroll id must be valid UUID' },
      { path: 'data.0.payroll_file.id', type: 'uuid', message: 'payroll_file id must be valid UUID' },
      { path: 'data.0.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
      { path: 'count', type: 'equals', expected: 100, message: 'count must be 100' },
    ],
  },
  {
    name: 'Staff portal payroll verify validation',
    user: 'staff',
    method: 'PATCH',
    url: '/api/staff-portal/payrolls/{{payroll_id}}/verify',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      otpCode: '999999',
      status: 1,
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'payroll id must be valid UUID' },
      { path: 'data.payroll_file.id', type: 'uuid', message: 'payroll_file id must be valid UUID' },
      { path: 'data.status', type: 'in', expected: [0, 1, 2], message: 'status must be in [0,1,2]' },
    ],
  },
  {
    name: 'Staff portal dashboard validation',
    user: 'staff',
    method: 'GET',
    url: '/api/staff-portal/dashboard',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.profile.fullName', type: 'equals', expected: 'Nilay Çoban', message: 'fullName must match' },
      { path: 'data.department.id', type: 'uuid', message: 'department id must be valid UUID' },
      { path: 'data.leaves.remaining', type: 'equals', expected: 14, message: 'remaining leaves must be 14' },
      { path: 'data.pendingApprovals.entrusts', type: 'equals', expected: 2, message: 'entrust approvals must be 2' },
    ],
  },
  {
    name: 'Files upload validation',
    user: 'admin',
    method: 'POST',
    url: '/api/files/upload',
    headers: {
      accept: 'application/json',
      'Content-Type': 'multipart/form-data',
    },
    data: {
      file: '@dummy.png',
      category: 'expense',
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 201, message: 'status must be 201' },
      { path: 'data.id', type: 'uuid', message: 'file id must be valid UUID' },
      { path: 'data.type', type: 'equals', expected: 'image', message: 'type must be image' },
    ],
  },
  {
    name: 'Files list validation',
    user: 'admin',
    method: 'GET',
    url: '/api/files',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'file id must be valid UUID' },
      { path: 'data.0.type', type: 'equals', expected: 'image', message: 'first file type must be image' },
      { path: 'count', type: 'equals', expected: 1204, message: 'count must be 1204' },
    ],
  },
  {
    name: 'Files detail validation',
    user: 'admin',
    method: 'GET',
    url: '/api/files/{{file_id}}',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'file id must be valid UUID' },
      { path: 'data.type', type: 'equals', expected: 'image', message: 'type must be image' },
      { path: 'data.category', type: 'equals', expected: 'expense', message: 'category must be expense' },
    ],
  },
  {
    name: 'Files delete validation',
    user: 'admin',
    method: 'DELETE',
    url: '/api/files/{{file_id}}',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.message', type: 'equals', expected: 'Dosya başarıyla silindi', message: 'message must match' },
    ],
  },
  {
    name: 'Staff create validation',
    user: 'admin',
    method: 'POST',
    url: '/api/staff',
    headers: {
      accept: 'application/json',
      'Content-Type': 'application/json',
    },
    data: {
      first_name: 'Ahmet',
      last_name: 'Yılmaz',
      domainID: '123e4567-e89b-12d3-a456-426614174000',
      phone_number: 5551234567,
      email: 'personel@firma.com',
      status: 1,
      is_user: false,
      departmentID: 'e5f7f2e4-8a2b-4e9a-bb8b-1c2d3e4f5a6b',
      profile: {
        nationID: '12345678901',
        gender: 'male',
        photo: {},
        about: 'string',
        address: {
          country: 'Türkiye',
          city: 'İstanbul',
          district: 'Kadıköy',
          address: 'Barbaros Bulvarı No:145 D:5',
        },
        birth_date: '1990-01-01',
        marital_status: 'single',
        child_number: 2,
        emergency: {
          name: 'Jane Doe',
          phone_number: '5551234567',
        },
        reference: 'string',
      },
      employment: {
        position: 'Yazılım Geliştirici',
        birth_place: 'Ankara',
        registered: {
          country: 'Türkiye',
          city: 'İstanbul',
          district: 'Kadıköy',
          address: 'Barbaros Bulvarı No:145 D:5',
        },
        is_fulltime: true,
        started_at: '2024-01-15',
        salary: 25000,
        iban: 'TR123456789012345678901234',
        registration_number: 'REG-2024-001',
        family: {
          father_name: 'John Doe',
          father_occupation: 'Engineer',
          mother_name: 'Jane Doe',
          mother_occupation: 'Doctor',
        },
        leave_day: 14,
      },
      education: {
        language_exams: [
          { name: 'YDS', lang: 'İngilizce', score: 92, year: 2020 },
          { name: 'IELTS', lang: 'İngilizce', score: 7, year: 2022 },
        ],
        military_service: {
          place: 'İstanbul',
          status: '1',
          date: '2020-06-01T00:00:00Z',
        },
        schools: [
          {
            name: 'İstanbul',
            type: 'university',
            degree: 'bachelor',
            field_of_study: 'Bilgisayar Mühendisliği',
            graduation_year: '2020-06-15T00:00:00.000Z',
          },
          {
            name: 'Ankara',
            type: 'university',
            degree: 'master',
            field_of_study: 'Gıda Mühendisliği',
            graduation_year: '2022-06-15T00:00:00.000Z',
          },
        ],
      },
      name: 'Ahmet Yılmaz',
      password: 'stringst',
      is_supervisor: true,
      onboarding_completed: true,
    },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'staff id must be valid UUID' },
      { path: 'data.email', type: 'equals', expected: 'personel@firma.com', message: 'email must match' },
      { path: 'data.profileCompletionPercentage', type: 'equals', expected: 75, message: 'profile completion must be 75' },
    ],
  },
  {
    name: 'Staff list validation',
    user: 'admin',
    method: 'GET',
    url: '/api/staff',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'staff id must be valid UUID' },
      { path: 'data.0.role', type: 'equals', expected: 'STAFF', message: 'role must be STAFF' },
      { path: 'count', type: 'equals', expected: 300, message: 'count must be 300' },
    ],
  },
  {
    name: 'Staff detail validation',
    user: 'admin',
    method: 'GET',
    url: '/api/staff/e50d8141-9952-462b-8f29-2083aa12d3b9?relations=profile&relations=education&relations=employment&relations=tracking&relations=department&relations=leaves&relations=expenses&relations=advances',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.id', type: 'uuid', message: 'staff id must be valid UUID' },
      { path: 'data.email', type: 'equals', expected: 'ozgur@ozel.com', message: 'email must match' },
      { path: 'data.profileCompletionPercentage', type: 'equals', expected: 38, message: 'profile completion must be 38' },
      { path: 'data.department.id', type: 'uuid', message: 'department id must be valid UUID' },
    ],
  },
  {
    name: 'Staff delete validation',
    user: 'admin',
    method: 'DELETE',
    url: '/api/staff/c4c55637-64aa-4376-ad31-ba6e92b98360',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.message', type: 'equals', expected: 'Personel silme başarılı', message: 'message must match' },
    ],
  },
  {
    name: 'Staff files list validation',
    user: 'admin',
    method: 'GET',
    url: '/api/staff/files/e0a35fc0-8375-4f2e-912f-5ecfa24a788b',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'data.0.id', type: 'uuid', message: 'file id must be valid UUID' },
      { path: 'data.0.staff_id', type: 'uuid', message: 'staff_id must be valid UUID' },
      { path: 'count', type: 'equals', expected: 0, message: 'count must be 0' },
    ],
  },
  {
    name: 'Staff export excel validation',
    user: 'admin',
    method: 'GET',
    url: '/api/staff/export/excel',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'fileUrl', type: 'notNull', message: 'fileUrl must not be null' },
      { path: 'totalRecords', type: 'equals', expected: 298, message: 'totalRecords must be 298' },
      { path: 'columns', type: 'exists', message: 'columns must exist' },
    ],
  },
  {
    name: 'Staff export pdf validation',
    user: 'admin',
    method: 'GET',
    url: '/api/staff/export/pdf?columns=first_name&columns=last_name&columns=email&columns=phone_number&columns=department&columns=status&columns=is_user&columns=created_at&columns=updated_at&columns=birth_date&columns=gender&columns=marital_status&columns=nation_id&columns=address&columns=emergency_contact&columns=child_number&columns=photo&columns=about&columns=reference&columns=position&columns=is_fulltime&columns=started_at&columns=birth_place&columns=family&columns=salary&columns=iban&columns=registration_number&columns=registered_location&columns=department_location&columns=language_exams&columns=military_service&columns=schools',
    headers: { accept: 'application/json' },
    assertions: [
      { path: 'success', type: 'equals', expected: true, message: 'success must be true' },
      { path: 'status', type: 'equals', expected: 200, message: 'status must be 200' },
      { path: 'fileUrl', type: 'notNull', message: 'fileUrl must not be null' },
      { path: 'totalRecords', type: 'equals', expected: 298, message: 'totalRecords must be 298' },
      { path: 'exportedAt', type: 'notNull', message: 'exportedAt must not be null' },
    ],
  },
];

// Group tests by HTTP method for easier navigation/debugging
export const testsByMethod = tests.reduce<Record<string, any[]>>((acc, test) => {
  const method = (test.method || 'GET').toUpperCase();
  if (!acc[method]) acc[method] = [];
  acc[method].push(test);
  return acc;
}, {});

export const getTests = testsByMethod.GET || [];
export const postTests = testsByMethod.POST || [];
export const putTests = testsByMethod.PUT || [];
export const patchTests = testsByMethod.PATCH || [];
export const deleteTests = testsByMethod.DELETE || [];

export default tests;
